spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.29.32.1:8082/realms/selmag
        registration:
          keycloak:
            client-id: admin-service
            client-secret: t75kL7wVkDgope3rsyNw9jYxO1HsqhGG
            authorization-grant-type: client_credentials
            scope:
              - metrics
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: t75kL7wVkDgope3rsyNw9jYxO1HsqhGG
            scope:
              - metrics
              - openid
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: t75kL7wVkDgope3rsyNw9jYxO1HsqhGG
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://172.29.32.1:8082/realms/selmag
management:
  endpoints:
    web:
      exposure:
        include: #какие метрики должны быть общедоступными
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.29.32.1:8761/eureka
    register-with-eureka: false
